<?php 
    $question_list = array(
        "Q1" => array("question" =>   'I like to work on cars',                                 "answer" => "r"),
        "Q2" => array("question" =>  'I like to do puzzles',                                    "answer" => "i"),
        "Q3" => array("question" =>  'I am good at working independently',                      "answer" => "a"),
        "Q4" => array("question" =>  'I like to work in teams',                                 "answer" => "s"),
        "Q5" => array("question" =>  'I am an ambitious person), I set goals for myself',       "answer" => "e"),
        "Q6" => array("question" =>  'I like to organize things), (files), desks/offices)',     "answer" => "c"),
        "Q7" => array("question" =>  'I like to build things',                                  "answer" => "r"),
        "Q8" => array("question" =>  'I like to read about art and music',                      "answer" => "a"),
        "Q9" => array("question" =>  'I like to have clear instructions to follow',             "answer" => "c"),
        "Q10" => array("question" => 'I like to try to influence or persuade people',           "answer" => "e"),
        "Q11" => array("question" => 'I like to do experiments',                                "answer" => "i"),
        "Q12" => array("question" => 'I like to teach or train people',                         "answer" => "s"),
        "Q13" => array("question" => 'I like trying to help people solve their problems',       "answer" => "s"),
        "Q14" => array("question" => 'I like to take care of animals',                          "answer" => "r"),
        "Q15" => array("question" => "I wouldn't mind working 8 hours per day in an office",    "answer" => "c"),
        "Q16" => array("question" => "I like selling things",                                   "answer" => "e"),
        "Q17" => array("question" => 'I enjoy creative writing',                                "answer" => "a"),
        "Q18" => array("question" => 'I enjoy science',                                         "answer" => "i"),
        "Q19" => array("question" => 'I am quick to take on new responsibilities',              "answer" => "e"),
        "Q20" => array("question" => 'I am interested in healing people',                       "answer" => "s"),
        "Q21" => array("question" => 'I enjoy trying to figure out how things work',            "answer" => "i"),
        "Q22" => array("question" => 'I like putting things together or assembling things',     "answer" => "r"),
        "Q23" => array("question" => 'I am a creative person',                                  "answer" => "a"),
        "Q24" => array("question" => 'I pay attention to details',                              "answer" => "c"),
        "Q25" => array("question" => 'I like to do filing or typing',                           "answer" => "c"),
        "Q26" => array("question" => 'I like to analyze things (problems/situations)',          "answer" => "i"),
        "Q27" => array("question" => 'I like to play instruments or sing',                      "answer" => "a"),
        "Q28" => array("question" => 'I enjoy learning about other cultures',                   "answer" => "s"),
        "Q29" => array("question" => 'I would like to start my own business',                   "answer" => "e"),
        "Q30" => array("question" => 'I like to cook',                                          "answer" => "r"),
        "Q31" => array("question" => 'I like acting in plays',                                  "answer" => "a"),
        "Q32" => array("question" => 'I am a practical person',                                 "answer" => "r"),
        "Q33" => array("question" => 'I like working with numbers or charts',                   "answer" => "i"),
        "Q34" => array("question" => 'I like to get into discussions about issues',             "answer" => "s"),
        "Q35" => array("question" => 'I am good at keeping records of my work',                 "answer" => "c"),
        "Q36" => array("question" => 'I like to lead',                                          "answer" => "e"),
        "Q37" => array("question" => 'I like working outdoors',                                 "answer" => "r"),
        "Q38" => array("question" => 'I would like to work in an office',                       "answer" => "c"),
        "Q39" => array("question" => "I'm good at math",                                        "answer" => "i"),
        "Q40" => array("question" => 'I like helping people',                                   "answer" => "s"),
        "Q41" => array("question" => 'I like to draw',                                          "answer" => "a"),
        "Q42" => array("question" => 'I like to give speeches',                                 "answer" => "e")
    );


